# config/gait_parameters.yaml
gait_parameters:
  walk:
    stride_length: 0.2
    swing_height: 0.05
    frequency: 1.0
  
  trot:
    stride_length: 0.3
    swing_height: 0.08
    frequency: 1.5
  
  crawl:
    stride_length: 0.1
    swing_height: 0.03
    frequency: 0.5